name: update

on:
  push:
    branches: [main]
  schedule:
    - cron: "5 5 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cp .env.example .env
      - run: npm install
      - run: sudo npm install -g npm-check-updates
      - run: npm-check-updates "/grouparoo/" -u
      - run: npm install
      - name: store-core-version
        run: echo CORE_VERSION=`cat package.json | jq -r '.dependencies."@grouparoo/core"'` >> $GITHUB_ENV
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updating Packages to v${{ env.CORE_VERSION }}
          commit_user_name: Grouparoo Bot
          commit_user_email: hello@grouparoo.com
          commit_author: Grouparoo Bot <hello@grouparoo.com>
          branch: ${{ github.head_ref }}
          tagging_message: v${{ env.CORE_VERSION }}
